### ISSUE TITLE
[Bug] Fails to detect compile_commands.json

### ISSUE THREAD

**Issue by papadokolos** [pieterverstraete/include_autocomplete#4]
### Brief Description
The recently added feature of auto-detecting a `compile_commands.json` fails to find my compilation databse file.

### Technical Details
It seems that prior to checking for a `compile_commands.json` existance, there is a check for the settings `ecc_flags_sources`, `easy_clang_complete_flags_sources`, and `compile_commands`. This is great, but it skips EasyClangComplete's User settings file.

If you want to fully support EasyClangComplete, you need to check for the Default and the User settings files of the plugin, which can't be accessed via `view.settings().get()`, but only via `sublime.load_settings("EasyClangComplete.sublime-settings").get()` (as described [here](https://stackoverflow.com/a/14186945)).

I, for example, put my settings there (_.../sublime-text-3/Packages/User/EasyClangComplete.sublime-settings_); hence why my compilation database is left undetected.

**Edit:**
Moreover, my sublime-project file contains multiple folders as "path" setting, and the current logic only searches the compilation database at the last directory mentioned in the project file when setting `"compilation_database": "${project_path}"`.

### My System Specification
- **Operating System:**
    Ubuntu 14.04 32bit (VirtualBox)
- **Sublime Text Version:**
    Sublime Text 3 Build 3126

**Comment by pieterverstraete** [comment]
Thanks for the feedback. I am leaving on holiday tomorrow, but I will definitely look at it when I get back.

**Comment by pieterverstraete** [comment]
I think I fixed it, but I don't use EasyClangComplete myself, so I can't verify that it's working. Would you be willing to check this?

**Comment by rwols** [comment]
Sorry for being silent on this, this went under the radar for me.

I implemented this for my particular use-case. I always use a sublime-project with settings specific to the particular project in question, so it makes sense to me to write where your compilation database lives in your sublime-project file.

With the advent of the language server protocol, I switched to the wonderful `clangd` for my language smartness needs, so I don't invest my time in ECC anymore. I thank @pieterverstraete for attempting to solve your issue.

**Comment by papadokolos** [comment]
> Would you be willing to check this?

Sure! Unfortunately I'm currently on a holiday, so I guess I'll be able to check this next weekend.

> With the advent of the language server protocol, I switched to the wonderful clangd

Very interesting. I didn't know that this project has already gain the functionality of ECC. I must give it a look.

**Comment by papadokolos** [comment]
> I think I fixed it, but I don't use EasyClangComplete myself, so I can't verify that it's working. Would you be willing to check this?

I can't find your commit/s regarding the fix you are talking about. Perhaps you forgot to push your changes? :smiling_imp:

**Comment by pieterverstraete** [comment]
Sorry for the delay, I committed the change. Thanks for wanting to test it out :)
